/* Per-lesson depth: the mechanism behind the idea, and the mistake people
   actually make. Indexed by course id, in lesson order. */

export type LessonDepth = {
  detail: string;
  pitfall: string;
};

export const lessonDepth: Record<string, LessonDepth[]> = {
  "data-literacy": [
    {
      detail:
        "The mean and the median fail differently, and that difference is mechanical rather than stylistic. The mean sums every value and divides, so each observation contributes in proportion to its size — one stay of 60 days moves it as much as thirty stays of two days. The median only cares about position: sort the values and take the middle one, and an extreme value counts once no matter how extreme it is. So when the two summaries disagree, that disagreement is itself a measurement. It is telling you the distribution is not symmetric, and the size of the gap roughly tracks how much weight sits in the tail.",
      pitfall:
        "Reporting the mean because it is the default, then describing it as the typical patient. In a skewed distribution the mean can sit in a region where almost nobody actually falls.",
    },
    {
      detail:
        "Measurement level is a claim about what the numbers stand for, and it decides which operations preserve meaning. With nominal values the labels are arbitrary, so any arithmetic on their codes is arithmetic on the coding scheme rather than on the world. Ordinal values carry order but not distance, so you can rank and take a median but an average assumes spacing that was never established. Interval and ratio values support the full range of arithmetic because equal differences really do mean equal amounts. The storage type in the database tells you none of this — only the definition of the field does.",
      pitfall:
        "Letting a numeric code decide the analysis. If discharge disposition is stored as 1, 2, 3, software will happily compute an average of 1.8 that corresponds to no clinical category at all.",
    },
    {
      detail:
        "An outlier is a statement about a value's relationship to a distribution, not an intrinsic property of the value. That is why the investigation is always the same sequence: confirm the units, confirm the timestamp, confirm the source system, then confirm the clinical context. Each check can explain the value entirely — a lab reported in different units, a specimen drawn during a procedure, a device feeding a different scale. Deleting first destroys exactly the cases most likely to be informative, because genuine extreme values and genuine data errors look identical until you trace them.",
      pitfall:
        "Applying an automatic rule such as dropping anything beyond three standard deviations. That rule removes real physiology and real errors at the same rate, and leaves no record of which was which.",
    },
    {
      detail:
        "Missing data is generated by a process, and the shape of the missingness tells you which process. If values are missing at random, dropping those rows costs precision but leaves the conclusion unbiased. If missingness depends on something related to the outcome — a test ordered only when a patient looks unwell, a field skipped in rushed intakes — then the rows that remain are a filtered population, and every summary computed from them answers a question about that filtered group instead. This is why the pattern gets described before anything is deleted or imputed: both choices silently redefine who the analysis is about.",
      pitfall:
        "Treating complete-case analysis as the neutral option. Dropping incomplete rows is itself a decision, and it is the one most likely to remove the patients whose care differed.",
    },
  ],

  "python-reasoning": [
    {
      detail:
        "An assignment is not an equation; it is an instruction with an order. The right-hand side is evaluated first using the current bindings, and only then is the name rebound to the result. That is why total = total + 3 is not a contradiction: the total on the right is the old value, and the total on the left is a new binding. Tracing on paper forces this order to be explicit, which is exactly what guessing skips.",
      pitfall:
        "Reading a program as a set of simultaneous facts rather than a sequence of updates, and so expecting a variable to reflect a change that happens on a later line.",
    },
    {
      detail:
        "A conditional commits the program to exactly one path, so the boundary of the condition is where behaviour changes. Off-by-one errors live at that boundary because >= and > differ only for a single value, and that value is often the one that matters in practice. Testing the boundary directly — the value just below, the value itself, the value just above — checks the claim the condition is making rather than the case you happened to imagine.",
      pitfall:
        "Testing only comfortable middle-of-the-range inputs, which pass under both the correct and the incorrect comparison operator.",
    },
    {
      detail:
        "A function is a testable claim when it has one job and its result depends only on its inputs. That is what makes a failing test informative: if the function does one thing, a failure points at one thing. Functions that read hidden state or do several jobs at once produce failures that could have come from anywhere, so the test tells you something broke without telling you what.",
      pitfall:
        "Writing one large test that exercises several behaviours at once. It fails on the first problem and hides the rest, so each fix reveals another failure instead of finishing the job.",
    },
    {
      detail:
        "Debugging is a search for the assumption that stopped being true, not a search for a bad line. The line that raises the error is usually where a wrong value arrived, while the defect is wherever that value was produced. Working backwards — reproduce it, then bisect the input or the code path until the smallest failing case remains — converts a vague failure into a specific false belief you can correct.",
      pitfall:
        "Changing code before reproducing the failure reliably. Without a reproduction you cannot tell a fix from a coincidence.",
    },
  ],

  cybersecurity: [
    {
      detail:
        "Threat modelling runs in a fixed order because each step constrains the next. Assets define what loss would mean; actors define who is motivated to cause it and with what resources; paths are the concrete routes from those actors to those assets; controls close specific paths. Reversing the order produces security theatre — controls chosen for familiarity rather than for the path they interrupt, protecting things nobody was targeting while the real route stays open.",
      pitfall:
        "Starting from a checklist of controls. It produces defences that are individually reasonable and collectively unmatched to anything a real adversary would do.",
    },
    {
      detail:
        "Social engineering works on process, not on gullibility. The recurring pattern is manufactured urgency plus a request to bypass a normal check, because pressure is what stops people from verifying. The reliable defence is structural rather than perceptual: verify through a channel the message did not choose. A phone number in a suspicious email reaches whoever sent the email, while the number already in your directory does not.",
      pitfall:
        "Judging a message by how professional it looks. Presentation is the cheapest thing for an attacker to get right, and increasingly it is automated.",
    },
    {
      detail:
        "Least privilege is a blast-radius argument rather than a statement of distrust. Every account is eventually going to be compromised or misused by accident, and the damage it can do at that moment is exactly the access it holds. Granting broad permissions because it is convenient today creates a standing liability, and permissions almost never get revoked on their own — access accumulates as people change roles.",
      pitfall:
        "Granting admin to unblock someone quickly and treating it as temporary. Temporary access without an expiry is permanent access with better intentions.",
    },
    {
      detail:
        "Incident response has an order of operations because the steps interfere with each other. Containment limits damage but the fastest containment — wiping and rebuilding — destroys the evidence needed to establish scope. Preserving logs and images first is what lets you answer the question that actually matters afterwards: what else did they reach, and when. The post-incident review is the step that turns one incident into a control.",
      pitfall:
        "Rebuilding the affected machine immediately. It feels decisive and it removes any chance of learning how far the intrusion went.",
    },
  ],

  algorithms: [
    {
      detail:
        "Complexity analysis counts operations as a function of input size because that is the part that survives changing hardware. Constant factors and machine speed shift the curve up or down; the growth term changes its shape. This is why an algorithm that is slower on today's small input can be the only viable option at ten times the scale, and why timing a single run on one machine answers a different question than the one you asked.",
      pitfall:
        "Benchmarking on inputs far smaller than production. At small n almost every approach looks acceptable, which is exactly when the wrong one gets chosen.",
    },
    {
      detail:
        "Growth rates dominate eventually, and 'eventually' arrives sooner than intuition suggests. Between linear and quadratic, ten times the data is ten times the work versus a hundred times the work — the gap is not a matter of tuning. What makes this practical rather than theoretical is that you can identify the growth term by inspection: count how many times the work repeats as the input grows, and ignore everything that does not scale.",
      pitfall:
        "Optimising constant factors in a quadratic method instead of changing the method. Halving the constant buys one doubling of input size, once.",
    },
    {
      detail:
        "Structure is what allows an algorithm to skip work legitimately. Binary search is fast only because sortedness guarantees that everything on one side of the comparison can be discarded; the same code on unsorted data is not slow but wrong. This is the general shape of algorithmic speedups — a precondition you maintain in exchange for work you no longer have to do, which is why maintaining the precondition is part of the cost.",
      pitfall:
        "Using a method whose precondition has quietly stopped holding, such as searching a list that another code path has since appended to.",
    },
    {
      detail:
        "Every algorithmic choice spends one resource to buy another: memory for speed, preprocessing for query time, simplicity for throughput. A defensible decision names both sides and the constraint that decides between them, because the same tradeoff resolves differently under different workloads. A read-heavy system and a write-heavy system with identical data can correctly choose opposite structures.",
      pitfall:
        "Defending a choice by its best-case behaviour alone. The cost you did not mention is the one that shows up in production.",
    },
  ],

  "sql-modeling": [
    {
      detail:
        "A schema is a claim about the world, and the grain — what exactly one row represents — is the load-bearing part of that claim. One row per patient and one row per visit support different questions, and a query that assumes the wrong grain returns a number that looks fine and answers nothing. Keys and constraints exist to keep the claim true as real data arrives, which is why they belong in the model rather than in application code.",
      pitfall:
        "Leaving the grain implicit. Everyone assumes a different one, and the resulting counts disagree without anybody being able to say why.",
    },
    {
      detail:
        "SQL executes in a different order from the one you write. FROM establishes the rows, WHERE filters individual rows, GROUP BY collapses them, and only then does filtering on aggregates apply. This matters because filtering before grouping changes who is counted within each group, while filtering after grouping removes entire groups. Both are legitimate, and they answer questions that differ in a way no amount of squinting at the result set will reveal.",
      pitfall:
        "Moving a condition between WHERE and HAVING to make an error go away, without noticing the question changed.",
    },
    {
      detail:
        "A join changes your population in two directions at once. Missing matches drop rows on an inner join, and duplicate matches on the many side multiply them. Both happen silently, which is why the discipline is to know the expected row count before joining and check it after. An aggregate computed over a join that quietly duplicated rows is not slightly off; it is a sum over a population that never existed.",
      pitfall:
        "Trusting a total after a join without re-checking the row count. Double-counting produces plausible numbers, which is what makes it dangerous.",
    },
    {
      detail:
        "An aggregate summarises whichever rows survived every earlier step, so auditing means reconstructing that path: how many rows started, what the filters removed, what the joins added or dropped, and what NULLs did to the arithmetic. Aggregate functions skip NULLs rather than treating them as zero, so an average can rise simply because the low values were missing rather than because anything improved.",
      pitfall:
        "Reading AVG as the average over everyone. It is the average over everyone who had a value, which is a different group whenever data is missing unevenly.",
    },
  ],

  "data-visualization": [
    {
      detail:
        "Chart choice follows from the question, because each form encodes data in a way that makes one comparison easy and the others hard. Position along a common scale is the most accurately read encoding, which is why bar and dot charts win for comparing groups. Area and angle are read far less accurately, which is why pie charts fail as soon as the slices are close in size or numerous.",
      pitfall:
        "Choosing the chart first and fitting the question to it. The result is usually a chart that is technically accurate and answers nothing anyone asked.",
    },
    {
      detail:
        "A bar chart encodes value as length, so the baseline is part of the encoding rather than a formatting choice. Truncating the axis breaks the correspondence between length and quantity, and the resulting exaggeration is proportional to how much was cut off. Line charts differ because they encode change rather than magnitude, which is why a non-zero baseline can be honest there and misleading in a bar chart.",
      pitfall:
        "Reading the gap between bars before locating the baseline. The visual difference may be entirely an artefact of where the axis starts.",
    },
    {
      detail:
        "A point estimate reported alone communicates a precision the data does not have. The interval carries the information about how much the estimate could move under resampling, and its width is often the finding — a wide band means the study cannot distinguish outcomes that would lead to different decisions. Showing that range is not hedging; it is reporting the actual result.",
      pitfall:
        "Dropping error bars because they make the chart look uncertain. The uncertainty exists either way; hiding it just moves the error into the reader's conclusion.",
    },
    {
      detail:
        "Defending a chart means stating the choices that make its comparison fair — shared scale, shared units, comparable groups, a time window chosen for a reason — and naming the ones that could be challenged. This is a design practice, not a rhetorical one: a chart whose construction survives being read out loud is one you can put in front of a sceptical audience.",
      pitfall:
        "Selecting the time window after seeing which window makes the point. The chart becomes an argument about the window rather than about the data.",
    },
  ],

  "statistical-inference": [
    {
      detail:
        "A p-value is computed inside an assumed world: the one where there is no real effect. It reports how often that world would produce a result at least as extreme as yours. That is all it reports. It is not the probability that the null hypothesis is true, not the probability your finding is real, and not a measure of effect size — a trivial difference reaches any threshold given a large enough sample.",
      pitfall:
        "Reading a small p-value as evidence that the effect is large or important. It speaks to detectability, not to magnitude.",
    },
    {
      detail:
        "A confidence interval is the range of effects the data cannot rule out, and its width carries as much information as its centre. The practical test is decision-based: look at both ends and ask whether they would lead to the same action. If one end means adopt and the other means abandon, the study has not answered the question regardless of where the point estimate happens to sit.",
      pitfall:
        "Treating the point estimate as the finding and the interval as decoration. The interval is the finding.",
    },
    {
      detail:
        "Sampling determines who a conclusion is about, and every step between the intended population and the analysed rows can change that. Non-response, eligibility filters, and attrition each remove people, and the question is never how many were lost but whether the losses were related to the outcome. Systematic loss produces bias that a larger sample makes more precise rather than more correct.",
      pitfall:
        "Assuming a large sample fixes a biased one. Increasing n narrows the interval around the wrong number.",
    },
    {
      detail:
        "Random variation alone produces differences between groups, so the real question is whether an observed difference is larger than chance routinely manages. That is why effect size and statistical significance are separate: significance says the difference is detectable given your sample, while effect size says whether it is big enough to matter. A study can establish the first and be silent on the second.",
      pitfall:
        "Declaring a result meaningful because it cleared a threshold, without ever asking how large the effect was in units anyone cares about.",
    },
  ],

  "ml-foundations": [
    {
      detail:
        "A model's score on data it trained on measures memorisation as much as learning, which is why evaluation requires data the model has never seen. The validation set is used to make choices, so it stops being an honest estimate as soon as you tune against it. The test set is spent the first time you look at it — every subsequent decision informed by that number turns it into another validation set, and the reported performance drifts upward while the real performance does not.",
      pitfall:
        "Checking the test set repeatedly during development. The number keeps improving because you are fitting to it, not because the model is.",
    },
    {
      detail:
        "Data quality bounds model quality in a way no architecture can escape. Leakage is the sharpest version: a feature that encodes the answer, or that would not exist at prediction time, produces excellent offline scores and collapses in production. Mislabelled examples set a ceiling on achievable accuracy, and biased collection means the model faithfully learns a pattern that was never about the world.",
      pitfall:
        "Reacting to an unexpectedly high score by shipping it. Results that look too good usually mean a feature is carrying information it should not have.",
    },
    {
      detail:
        "Accuracy averages over error types that have different real costs. On imbalanced problems it is actively misleading — predicting the majority class every time can score well while being useless. Precision and recall separate the two failure modes, and the choice between them is a statement about which harm you would rather absorb: a false alarm or a missed case.",
      pitfall:
        "Optimising a single default metric without asking what each error costs. The metric silently makes a decision that belongs to a human.",
    },
    {
      detail:
        "Deployment is when the distribution starts moving. Inputs shift as behaviour and processes change, and the relationship the model learned can decay even when the pipeline is healthy and nothing errors. That is why monitoring tracks input distributions and outcomes over time rather than just uptime, and why the retraining trigger is decided in advance — thresholds set during an incident are set under pressure.",
      pitfall:
        "Treating launch performance as a property of the model. It is a measurement of one moment, and it starts expiring immediately.",
    },
  ],

  "systems-design": [
    {
      detail:
        "At any moment one resource limits throughput, and work spent anywhere else buys nothing. This is why measurement precedes change: without a profile you are optimising the part that is easiest to reason about rather than the part that is constraining. The bottleneck also moves — fixing it promotes something else to the constraint — so the loop is measure, fix, re-measure rather than repeating whatever worked last time.",
      pitfall:
        "Adding capacity to the component that is easiest to scale. It raises cost and leaves throughput where it was.",
    },
    {
      detail:
        "A cache trades freshness for speed, and it only pays where the data is expensive to produce, stable enough to reuse, and read far more often than written. Caching cheap or fast-changing data adds an invalidation problem without a meaningful saving. The hard part is never the lookup; it is deciding when the copy stops being true and making sure every path that changes the underlying data knows about it.",
      pitfall:
        "Adding a cache to hide a slow query instead of fixing it. The slowness is still there, now with stale results on top.",
    },
    {
      detail:
        "Distributed systems fail partially and slowly rather than cleanly, which is why 'is it up' is the wrong question. A dependency that hangs is worse than one that fails fast, because callers hold connections and threads while waiting and the exhaustion propagates outward. Timeouts, retries with backoff, fallbacks, and load shedding are the decisions that determine whether one component's failure stays contained.",
      pitfall:
        "Retrying aggressively without backoff. It converts a struggling dependency into a failed one by adding load exactly when it cannot absorb any.",
    },
    {
      detail:
        "There is no best architecture, only one that fits stated constraints — expected load, consistency requirements, team size, operational budget, tolerance for downtime. A defensible design names the constraints, names what it optimises, and names what it gives up. That last part is what makes the decision revisitable when the constraints change, which they will.",
      pitfall:
        "Designing for a scale you do not have. The complexity arrives immediately and the load may never.",
    },
  ],

  "critical-thinking": [
    {
      detail:
        "Separating a claim from its evidence is mechanical: state what is being asserted in a form that could be false, then list separately what is offered in support. The separation matters because the two get conflated constantly — confidence, repetition, and detail all feel like support without being evidence. Once separated, you can evaluate the evidence on its own terms rather than on how convincingly it was delivered.",
      pitfall:
        "Judging a claim by the fluency of its presentation. Fluency is a property of the speaker, not of the evidence.",
    },
    {
      detail:
        "Naming a reasoning error means identifying the specific move that fails, usually the leap from premises to conclusion. That is more useful than labelling because it tells you what would fix the argument. It also keeps two questions apart that are easy to merge: whether the argument is good, and whether the conclusion is true. A bad argument for a true conclusion is common, and dismissing the conclusion because the argument was bad is its own error.",
      pitfall:
        "Using fallacy names as a way to stop thinking. The label ends the conversation without establishing anything about the claim.",
    },
    {
      detail:
        "Evaluating a source means asking what evidence it presents and how that evidence was produced, rather than how authoritative it sounds. Method carries the weight: sample, comparison group, and whether the measurement could have shown the opposite. Interests are worth knowing because they tell you where to look hardest, but a conflicted source can be right and a disinterested one can be wrong.",
      pitfall:
        "Substituting credentials for evidence in either direction — accepting a claim because of who made it, or rejecting it for the same reason.",
    },
    {
      detail:
        "Deciding in advance what would change your mind converts a belief into something testable. It has to be specific enough to recognise when it happens and fixed before the evidence arrives, because thresholds set afterwards move to accommodate whatever showed up. This is the practical difference between holding a position and defending one: the first can be updated, and the second only accumulates justifications.",
      pitfall:
        "Naming a disconfirming condition so demanding that nothing could ever meet it. That is a commitment wearing the costume of an open mind.",
    },
  ],
};
