"use client";

import { useState } from "react";

type Lesson = { id: string; unit: string; title: string; kind: string; prompt: string; choices: string[]; correct: number; explanation: string; hint: string };

const lessons: Lesson[] = [
  { id: "1.1", unit: "START HERE", title: "Spot the shape of a distribution", kind: "Quick check", prompt: "A length-of-stay dataset has a mean of 4 days and a median of 2 days. What is the best interpretation?", choices: ["The distribution is perfectly symmetric.", "A few longer stays may be pulling the mean upward.", "Every patient stayed exactly 2 days.", "The median is necessarily a data-entry error."], correct: 1, explanation: "Correct. When the mean is above the median, a smaller number of high values often pulls the average upward. This is a common sign of right skew.", hint: "Ask which summary measure is most affected by unusually large values." },
  { id: "1.2", unit: "DATA TYPES", title: "Identify the data type", kind: "Socratic lesson", prompt: "A discharge disposition is recorded as “home,” “skilled nursing facility,” or “hospice.” What kind of variable is this?", choices: ["Continuous, because the options describe a range of outcomes.", "Ordinal, because each location has a fixed clinical ranking.", "Categorical, because the values are labels rather than measurements.", "Binary, because there are two kinds of patients."], correct: 2, explanation: "Correct. Discharge disposition is categorical. The values name groups; there is no universal numerical scale from home to hospice.", hint: "Does each value measure an amount, or does it name a group?" },
  { id: "1.3", unit: "OUTLIERS", title: "Investigate before removing", kind: "Clinical scenario", prompt: "A patient record has a creatinine value of 14.0. What should you do first?", choices: ["Delete it automatically because it is an outlier.", "Replace it with the mean creatinine value.", "Check clinical context and related fields before deciding whether it is an error.", "Round it down because it is unusually high."], correct: 2, explanation: "Correct. Unusual does not mean wrong. A creatinine of 14.0 can be clinically plausible and vital to the analysis; inspect the record before applying any rule.", hint: "Separate an unusual observation from an impossible one." },
  { id: "1.4", unit: "MISSINGNESS", title: "Ask why data are absent", kind: "Practice", prompt: "Blood-pressure values are missing mostly for patients who left the clinic early. Which statement is most accurate?", choices: ["The data are missing completely at random.", "The missingness may be related to patient behavior or clinical workflow and could bias results.", "Missing values never affect validity if the sample is large.", "The correct action is always to delete those rows."], correct: 1, explanation: "Correct. Missingness tied to leaving early is unlikely to be random. It can distort who is represented in the analysis and should be examined before imputation or deletion.", hint: "Could the reason a value is missing be connected to the patient or the care process?" },
];

export default function Home() {
  const [screen, setScreen] = useState<"course" | "lesson" | "notes">("course");
  const [lessonIndex, setLessonIndex] = useState(0);
  const [choice, setChoice] = useState<number | null>(null);
  const [checked, setChecked] = useState(false);
  const [showHint, setShowHint] = useState(false);
  const [completed, setCompleted] = useState<number[]>([]);
  const [tutorReply, setTutorReply] = useState("");
  const [tutorLoading, setTutorLoading] = useState(false);
  const lesson = lessons[lessonIndex];
  const isCorrect = choice === lesson.correct;
  const mastery = Math.round((completed.length / lessons.length) * 100);

  function openLesson(index: number) { setLessonIndex(index); setChoice(null); setChecked(false); setShowHint(false); setTutorReply(""); setScreen("lesson"); }
  function checkAnswer() { if (choice !== null) setChecked(true); }
  function nextLesson() { if (isCorrect && !completed.includes(lessonIndex)) setCompleted([...completed, lessonIndex]); if (lessonIndex < lessons.length - 1) openLesson(lessonIndex + 1); else setScreen("course"); }
  async function askTutor() {
    setTutorLoading(true);
    try {
      const response = await fetch("/api/tutor", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: lesson.prompt, learnerAnswer: choice === null ? "No option selected yet." : lesson.choices[choice], hintLevel: showHint ? 1 : 0 }) });
      const payload = (await response.json()) as { reply?: string };
      setTutorReply(payload.reply || "Try selecting an answer, then ask me to help you test your reasoning.");
    } catch { setTutorReply("I could not reach the tutor just now. You can still use the structured hint and answer explanation."); }
    finally { setTutorLoading(false); }
  }

  return <main className="course-app">
    <header className="app-header"><button className="app-brand" onClick={() => setScreen("course")}><span>◉</span> SocraticAI</button><div className="header-path">Basic Data Literacy <b>/</b> Module 1</div><div className="header-progress"><span>{completed.length} / {lessons.length} skills</span><i><b style={{ width: `${mastery}%` }} /></i></div></header>
    <aside className="course-sidebar"><div className="course-title"><span className="course-mark">⌁</span><div><b>Basic Data Literacy</b><small>4 UNITS · 4 SKILLS</small></div></div><p className="sidebar-label">MODULE 1</p><h2>Prepare & Explore</h2><p className="sidebar-copy">Build the habit of inspecting data before analysis.</p><div className="sidebar-lessons">{lessons.map((item, index) => <button key={item.id} className={`${screen === "lesson" && index === lessonIndex ? "active" : ""} ${completed.includes(index) ? "done" : ""}`} onClick={() => openLesson(index)}><span>{completed.includes(index) ? "✓" : item.id}</span><p>{item.title}<small>{item.kind}</small></p></button>)}</div><div className="sidebar-mastery"><span>MODULE MASTERY</span><b>{mastery}%</b><i><em style={{ width: `${mastery}%` }} /></i></div></aside>
    {screen === "course" && <section className="course-main"><div className="course-hero"><p>MODULE 1 · DATA PREPARATION & EXPLORATION</p><h1>Prepare & Explore</h1><span>Before you model, compare, or conclude, learn to see the structure and limitations of the data in front of you.</span></div><section className="about-unit"><h2>About this module</h2><p>These four short lessons help clinicians identify data types, read distributions, investigate extreme values, and reason about missing information. Every skill includes an objective check and an explanation of the clinical reasoning behind it.</p></section><section className="skill-list"><h2>Module skills</h2>{lessons.map((item, index) => <button key={item.id} onClick={() => openLesson(index)}><span className={completed.includes(index) ? "skill-icon complete" : "skill-icon"}>{completed.includes(index) ? "✓" : "▹"}</span><div><b>{item.id} · {item.title}</b><small>{item.kind} · {item.unit}</small></div><em>{completed.includes(index) ? "Review" : index === 0 ? "Start" : "Practice"} →</em></button>)}</section></section>}
    {screen === "lesson" && <section className="lesson-main"><div className="lesson-breadcrumb">MODULE 1 <span>›</span> {lesson.unit} <span>›</span> {lesson.title}</div><div className="lesson-card"><div className="lesson-topline"><span>{lesson.kind.toUpperCase()}</span><span>SKILL {lessonIndex + 1} OF {lessons.length}</span></div><h1>{lesson.title}</h1><p className="lesson-prompt">{lesson.prompt}</p><div className="answer-list">{lesson.choices.map((item, index) => <button key={item} disabled={checked} onClick={() => setChoice(index)} className={`${choice === index ? "selected" : ""} ${checked && index === lesson.correct ? "correct" : ""} ${checked && choice === index && index !== lesson.correct ? "incorrect" : ""}`}><span>{String.fromCharCode(65 + index)}</span>{item}</button>)}</div>{showHint && !checked && <div className="hint-box"><b>Hint</b><p>{lesson.hint}</p></div>}{checked && <div className={`answer-feedback ${isCorrect ? "correct" : "incorrect"}`}><b>{isCorrect ? "Correct — nice reasoning." : "Not quite — let’s correct the reasoning."}</b><p>{isCorrect ? lesson.explanation : `The best answer is ${String.fromCharCode(65 + lesson.correct)}. ${lesson.explanation}`}</p></div>}</div><aside className="tutor-card"><span className="tutor-icon">✦</span><p>SOCRATIC TUTOR</p><h2>Think first.<br/>Then check.</h2><span>I’ll help you test your reasoning and give hints only when you need them.</span><button className="tutor-ask" onClick={askTutor} disabled={tutorLoading}>{tutorLoading ? "Thinking…" : "Ask the tutor"}</button>{tutorReply && <p className="tutor-reply">{tutorReply}</p>}<div><b>LEARNING LOOP</b><small>Choose → Check → Understand → Apply</small></div></aside><footer className="lesson-actions"><button className="hint-link" onClick={() => setShowHint(true)}>Need a hint?</button><span>{checked ? (isCorrect ? "Ready for the next skill" : "Review the explanation, then try the next skill") : "Choose one answer"}</span><button className="check-button" disabled={choice === null} onClick={checked ? nextLesson : checkAnswer}>{checked ? (lessonIndex === lessons.length - 1 ? "Finish module" : "Continue") : "Check answer"} <b>→</b></button></footer></section>}
    {screen === "notes" && <section className="course-main notes-screen"><p>YOUR NOTES</p><h1>Capture what changes your thinking.</h1><textarea placeholder="Write a clinical example, a question, or an insight from this module…" /></section>}
  </main>;
}
